"use client"

import { useState } from "react"
import { FileText, Download, Eye, Printer, Share2, Calendar, User, ArrowLeft, Filter } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

// Mock reports data
const mockReports = [
  {
    id: "RPT-001",
    title: "Medical Analysis Report - Chest X-Ray Patient 001",
    type: "medical",
    documentName: "Chest_X-Ray_Patient_001.dcm",
    patientName: "John Doe",
    generatedAt: "2025-01-20T10:30:00Z",
    confidence: 94,
    status: "completed",
    findings: ["Clear lung fields", "Normal cardiac silhouette", "No acute abnormalities"],
    content: `MEDICAL ANALYSIS REPORT

PATIENT INFORMATION:
Name: John Doe
Study Date: January 20, 2025
Examination: Chest X-Ray

CLINICAL FINDINGS:
The chest radiograph demonstrates clear lung fields bilaterally with no evidence of consolidation, pleural effusion, or pneumothorax. The cardiac silhouette appears within normal limits. No acute abnormalities are identified.

DIAGNOSTIC IMPRESSION:
Normal chest radiograph. No acute cardiopulmonary abnormalities detected.

RECOMMENDATIONS:
- Continue routine care
- Follow up as clinically indicated
- No immediate intervention required

Confidence Level: 94%
Generated by VisionaryCare AI Analysis System`,
  },
  {
    id: "RPT-002",
    title: "Patient Summary - Chest X-Ray Patient 001",
    type: "patient",
    documentName: "Chest_X-Ray_Patient_001.dcm",
    patientName: "John Doe",
    generatedAt: "2025-01-20T10:35:00Z",
    confidence: 94,
    status: "completed",
    findings: ["Normal results", "No concerns found"],
    content: `PATIENT SUMMARY

Dear John,

We have completed the analysis of your chest X-ray from January 20, 2025.

WHAT WE EXAMINED:
Your chest X-ray was carefully reviewed using advanced AI analysis to check your lungs and heart.

WHAT WE FOUND:
Good news! Your chest X-ray shows:
- Your lungs appear clear and healthy
- Your heart size looks normal
- No signs of infection or other problems

WHAT THIS MEANS:
Your chest X-ray results are normal. This means we didn't find any concerning changes that need immediate attention.

NEXT STEPS:
- Continue with your regular healthcare routine
- Your doctor will discuss these results with you
- No urgent follow-up is needed based on these findings

If you have any questions or concerns, please contact your healthcare provider.

Analysis Confidence: 94%`,
  },
]

export default function ReportsPage() {
  const [selectedReport, setSelectedReport] = useState<any>(null)
  const [filterType, setFilterType] = useState("all")
  const [searchTerm, setSearchTerm] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)

  const filteredReports = mockReports.filter((report) => {
    const matchesSearch =
      report.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      report.patientName.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesFilter = filterType === "all" || report.type === filterType
    return matchesSearch && matchesFilter
  })

  const generateNewReport = async (documentId: string, reportType: "medical" | "patient") => {
    setIsGenerating(true)
    // Simulate API call
    setTimeout(() => {
      setIsGenerating(false)
      // In real implementation, this would call the API and refresh the reports list
    }, 3000)
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="sm" asChild>
                <a href="/dashboard" className="flex items-center gap-2">
                  <ArrowLeft className="w-4 h-4" />
                  Back to Dashboard
                </a>
              </Button>
              <div>
                <h1 className="text-xl font-bold font-serif text-primary">Medical Reports</h1>
                <p className="text-sm text-muted-foreground">Generated analysis reports and summaries</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant="secondary">{filteredReports.length} Reports</Badge>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-6">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Reports List */}
          <div className="lg:col-span-1">
            <Card>
              <CardHeader>
                <CardTitle className="font-serif">Reports Library</CardTitle>
                <CardDescription>All generated medical reports and summaries</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Search and Filter */}
                <div className="space-y-2">
                  <Input
                    placeholder="Search reports..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                  />
                  <Select value={filterType} onValueChange={setFilterType}>
                    <SelectTrigger>
                      <Filter className="w-4 h-4 mr-2" />
                      <SelectValue placeholder="Filter by type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Reports</SelectItem>
                      <SelectItem value="medical">Medical Reports</SelectItem>
                      <SelectItem value="patient">Patient Summaries</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                {/* Reports List */}
                <div className="space-y-3">
                  {filteredReports.map((report) => (
                    <div
                      key={report.id}
                      className={`p-3 border rounded-lg cursor-pointer transition-colors hover:bg-muted/50 ${
                        selectedReport?.id === report.id ? "border-primary bg-primary/5" : ""
                      }`}
                      onClick={() => setSelectedReport(report)}
                    >
                      <div className="flex items-start justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <FileText className="w-4 h-4 text-primary" />
                          <Badge variant={report.type === "medical" ? "default" : "secondary"}>
                            {report.type === "medical" ? "Medical" : "Patient"}
                          </Badge>
                        </div>
                        <Badge className="bg-green-100 text-green-800 text-xs">{report.confidence}%</Badge>
                      </div>
                      <h4 className="font-medium text-sm mb-1 line-clamp-2">{report.title}</h4>
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <User className="w-3 h-3" />
                        <span>{report.patientName}</span>
                        <Calendar className="w-3 h-3 ml-2" />
                        <span>{new Date(report.generatedAt).toLocaleDateString()}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Report Viewer */}
          <div className="lg:col-span-2">
            {selectedReport ? (
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div>
                      <CardTitle className="font-serif">{selectedReport.title}</CardTitle>
                      <CardDescription>
                        Generated on {new Date(selectedReport.generatedAt).toLocaleString()}
                      </CardDescription>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button size="sm" variant="outline">
                        <Eye className="w-4 h-4 mr-1" />
                        Preview
                      </Button>
                      <Button size="sm" variant="outline">
                        <Download className="w-4 h-4 mr-1" />
                        Download PDF
                      </Button>
                      <Button size="sm" variant="outline">
                        <Printer className="w-4 h-4 mr-1" />
                        Print
                      </Button>
                      <Button size="sm" variant="outline">
                        <Share2 className="w-4 h-4 mr-1" />
                        Share
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <Tabs defaultValue="content" className="w-full">
                    <TabsList>
                      <TabsTrigger value="content">Report Content</TabsTrigger>
                      <TabsTrigger value="metadata">Metadata</TabsTrigger>
                      <TabsTrigger value="customize">Customize</TabsTrigger>
                    </TabsList>

                    <TabsContent value="content" className="space-y-4">
                      <div className="bg-white border rounded-lg p-6 min-h-[500px]">
                        <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">
                          {selectedReport.content}
                        </pre>
                      </div>
                    </TabsContent>

                    <TabsContent value="metadata" className="space-y-4">
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <label className="text-sm font-medium">Report ID</label>
                          <p className="text-sm text-muted-foreground">{selectedReport.id}</p>
                        </div>
                        <div>
                          <label className="text-sm font-medium">Document</label>
                          <p className="text-sm text-muted-foreground">{selectedReport.documentName}</p>
                        </div>
                        <div>
                          <label className="text-sm font-medium">Patient</label>
                          <p className="text-sm text-muted-foreground">{selectedReport.patientName}</p>
                        </div>
                        <div>
                          <label className="text-sm font-medium">Confidence</label>
                          <p className="text-sm text-muted-foreground">{selectedReport.confidence}%</p>
                        </div>
                        <div>
                          <label className="text-sm font-medium">Generated</label>
                          <p className="text-sm text-muted-foreground">
                            {new Date(selectedReport.generatedAt).toLocaleString()}
                          </p>
                        </div>
                        <div>
                          <label className="text-sm font-medium">Status</label>
                          <Badge className="bg-green-100 text-green-800">{selectedReport.status}</Badge>
                        </div>
                      </div>

                      <div>
                        <label className="text-sm font-medium mb-2 block">Key Findings</label>
                        <ul className="space-y-1">
                          {selectedReport.findings.map((finding: string, index: number) => (
                            <li key={index} className="text-sm flex items-start gap-2">
                              <span className="text-green-600 mt-1">•</span>
                              {finding}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </TabsContent>

                    <TabsContent value="customize" className="space-y-4">
                      <div className="space-y-4">
                        <div>
                          <label className="text-sm font-medium mb-2 block">Report Title</label>
                          <Input defaultValue={selectedReport.title} />
                        </div>
                        <div>
                          <label className="text-sm font-medium mb-2 block">Additional Notes</label>
                          <Textarea placeholder="Add any additional notes or comments..." />
                        </div>
                        <div>
                          <label className="text-sm font-medium mb-2 block">Report Template</label>
                          <Select defaultValue="standard">
                            <SelectTrigger>
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="standard">Standard Report</SelectItem>
                              <SelectItem value="detailed">Detailed Analysis</SelectItem>
                              <SelectItem value="summary">Executive Summary</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                        <Button className="w-full">Regenerate Report</Button>
                      </div>
                    </TabsContent>
                  </Tabs>
                </CardContent>
              </Card>
            ) : (
              <Card>
                <CardContent className="flex items-center justify-center h-[500px]">
                  <div className="text-center">
                    <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                    <h3 className="text-lg font-medium mb-2">Select a Report</h3>
                    <p className="text-muted-foreground">Choose a report from the list to view its content</p>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
